// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHIkuPpcf2xawfRxMynIOBkS0zROAIOyg',
    appId: '1:762128163426:web:4c1bd21bffa34af2c1273b',
    messagingSenderId: '762128163426',
    projectId: 'budgetbro-ce796',
    authDomain: 'budgetbro-ce796.firebaseapp.com',
    storageBucket: 'budgetbro-ce796.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOetSbQ5idQURXgVfDFzwosSdDlRbYKmY',
    appId: '1:762128163426:android:f4ab64716235eca0c1273b',
    messagingSenderId: '762128163426',
    projectId: 'budgetbro-ce796',
    storageBucket: 'budgetbro-ce796.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqiXL1GX_0-CllDNWG6e20Yb1zJTqCjsg',
    appId: '1:762128163426:ios:bd6cd73c08a12699c1273b',
    messagingSenderId: '762128163426',
    projectId: 'budgetbro-ce796',
    storageBucket: 'budgetbro-ce796.appspot.com',
    iosClientId: '762128163426-gkbo07mnqa0hbu91e7od0gbbr1rpntot.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetbro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqiXL1GX_0-CllDNWG6e20Yb1zJTqCjsg',
    appId: '1:762128163426:ios:bd6cd73c08a12699c1273b',
    messagingSenderId: '762128163426',
    projectId: 'budgetbro-ce796',
    storageBucket: 'budgetbro-ce796.appspot.com',
    iosClientId: '762128163426-gkbo07mnqa0hbu91e7od0gbbr1rpntot.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetbro',
  );
}
